name: Deploy to CapRover


on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=your-dockerhub-username/caprover-sample-react
          TAG=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
          echo "IMAGE_NAME=$IMAGE_NAME:$TAG" >> $GITHUB_ENV

      - name: Deploy to CapRover
        uses: caprover/deploy-to-caprover-action@v1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: caprover-sample-react
          token: ${{ secrets.CAPROVER_TOKEN }}
          image: ${{ env.IMAGE_NAME }}

