name: Deploy to CapRover

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/caprover-sample-react
          TAG=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
          echo "IMAGE_NAME=$IMAGE_NAME:$TAG" >> $GITHUB_ENV

      - name: Deploy to CapRover
        run: |
          IMAGE=${{ env.IMAGE_NAME }}
          echo "Deploying image: $IMAGE"
          curl -X POST "${{ secrets.CAPROVER_SERVER }}/api/v2/apps/appData" \
            -H "Content-Type: application/json" \
            -H "X-Api-Token: ${{ secrets.CAPROVER_TOKEN }}" \
            -d '{
              "appName": "caprover-sample-react",
              "newImageName": "'"$IMAGE"'"
            }'

